admin:
  access_log_path: "/tmp/admin_access.log"
  address: 
    socket_address: 
      address: "0.0.0.0"
      port_value: 9901
static_resources: 
  listeners:
    - 
      name: "ingress"
      address: 
        socket_address: 
          address: "0.0.0.0"
          port_value: 443
      filter_chains:
          filters: 
            - 
              name: "envoy.http_connection_manager"
              config:
                stat_prefix: "ingress"
                codec_type: "AUTO"
                generate_request_id: true
                route_config: 
                  name: "local_route"
                  virtual_hosts: 
                    - 
                      name: "https-route"
                      domains: 
                        - "*"
                      routes: 
                        - 
                          match: 
                            prefix: "/user-security/"
                          route:
                            cluster: "usersecurityservice"
                            prefix_rewrite: "/"
                        - 
                          match: 
                            prefix: "/basic-display/"
                          route:
                            cluster: "basicdisplayservice"
                            prefix_rewrite: "/"
                        -  
                          match: 
                            prefix: "/"
                          route:
                            cluster: "nextclientservice"
                            prefix_rewrite: "/"
                http_filters:
                  - 
                    name: "envoy.router"
          tls_context:
            common_tls_context:
              tls_certificates:
                - certificate_chain:
                    filename: "/etc/tls-secret/server.crt"
                  private_key:
                    filename: "/etc/tls-secret/server.key"
  clusters:
    - 
      name: "usersecurityservice"
      connect_timeout: "0.25s"
      type: "strict_dns"
      lb_policy: "ROUND_ROBIN"
      hosts:
        - 
          socket_address: 
            address: "host.docker.internal"
            port_value: 18080
    - 
      name: "basicdisplayservice"
      connect_timeout: "0.25s"
      type: "strict_dns"
      lb_policy: "ROUND_ROBIN"
      hosts:
        - 
          socket_address: 
            address: "host.docker.internal"
            port_value: 28080
    - 
      name: "nextclientservice"
      connect_timeout: "0.25s"
      type: "strict_dns"
      lb_policy: "ROUND_ROBIN"
      hosts:
        - 
          socket_address: 
            address: "host.docker.internal"
            port_value: 3000