version: '3.1'

services:
 # user_security:
 #   build:
 #     context: service
 #     dockerfile: src/main/resources/Dockerfile
 #   ports:
  #    - "8080:8080"
  user_security_db:
    build:
      context: UserSecurityDB
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_PASSWORD: "changeme"
      POSTGRES_USER: "postgres"
    ports:
      - "15432:5432"
    networks:
      - net
  basic_display_db:
    build:
      context: db
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_PASSWORD: "changeme"
      POSTGRES_USER: "postgres"
    ports:
      - "25432:5432"
    networks:
      - net
networks:
  net:
