version: '3.1'

services:

  # front_service
  front-envoy:
    image: envoyproxy/envoy-alpine:v1.7.0
    volumes:
      - ./Envoy/envoy-config.yaml:/etc/envoy-config.yaml
      - ./Envoy/tls-secret/server.key:/etc/tls-secret/server.key
      - ./Envoy/tls-secret/server.crt:/etc/tls-secret/server.crt
    ports:
      - "443:443"
      - "80:80"
      - "9901:9901"
    command: "/usr/local/bin/envoy -c /etc/envoy-config.yaml --v2-config-only -l info --service-cluster 'gateway' --service-node 'gateway' --log-format '[METADATA][%Y-%m-%d %T.%e][%t][%l][%n] %v'"
    networks:
      - net

  # usersecurityservice:
  #   hostname: usersecurityservice
  #   image: user_security_service:latest
  #   ports:
  #     - "18080:18080"

  # basicdisplayservice:
  #   hostname: usersecurityservice
  #   image: user_security_service:latest
  #   ports:
  #     - "28080:28080"

  usersecuritydb:
    hostname: usersecuritydb
    image: postgres:14.1
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "changeme"
      POSTGRES_USER: "postgres"
      PGPORT: 15432
    ports:
      - "15432:15432"
    networks:
      - net

  basicdisplaydb:
    hostname: basicdisplaydb
    image: postgres:14.1
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "changeme"
      POSTGRES_USER: "postgres"
      PGPORT: 25432
    ports:
      - "25432:25432"
    networks:
      - net
      
  # # web_frontend
  # webfrontendservice:
  #   hostname: webfrontendservice
  #   image: client_service:latest
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - net

networks:
  net:
