apiVersion: apps/v1
kind: Deployment
metadata:
  name: eds-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eds_service
  template:
    metadata:
      labels:
        app: eds_service
    spec:
      containers:
      - name: eds-service
        image: katacoda/eds_server
        ports:
        - containerPort: 8080
          name: svc-port
          protocol: TCP