apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-envoy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front_envoy
  template:
    metadata:
      labels:
        app: front_envoy
    spec:
      containers:
      - name: envoy
        image: envoyproxy/envoy-alpine:v1.7.0
        ports:
          - containerPort: 9901
            protocol: TCP
            name: envoy-admin
          - containerPort: 443
            protocol: TCP
            name: envoy-web
        volumeMounts:
          - name: envoy-config
            mountPath: /etc/envoy-config
            readOnly: true
          - name: tls-secret
            mountPath: /etc/tls-secret
            readOnly: true
        command: ["/usr/local/bin/envoy"]
        args: ["-c", "/etc/envoy-config/envoy-config.yaml", "--v2-config-only", "-l", "info","--service-cluster","front-envoy","--service-node","front-envoy", "--log-format", "[METADATA][%Y-%m-%d %T.%e][%t][%l][%n] %v"]
      volumes:
        - name: envoy-config
          configMap:
            name: envoy-config
        - name: tls-secret
          secret:
            secretName: tls-secret