apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-security-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user_security_service
  template:
    metadata:
      labels:
        app: user_security_service
    spec:
      containers:
      - name: user-security-service
        image: user_security_service:latest
        ports:
        - containerPort: 8080
          name: svc-port
          protocol: TCP
      - name: envoy
        image: envoyproxy/envoy:latest
        ports:
          - containerPort: 9901
            protocol: TCP
            name: envoy-admin
          - containerPort: 8786
            protocol: TCP
            name: envoy-web
        volumeMounts:
          - name: envoy-config-volume
            mountPath: /etc/envoy-config/
        command: ["/usr/local/bin/envoy"]
        args: ["-c", "/etc/envoy-config/config.yaml", "--v2-config-only", "-l", "info","--service-cluster","user_security_service","--service-node","user_security_service", "--log-format", "[METADATA][%Y-%m-%d %T.%e][%t][%l][%n] %v"]
      volumes:
        - name: envoy-config-volume
          configMap:
            name: sidecar-config
            items:
              - key: envoy-config
                path: config.yaml