apiVersion: apps/v1
kind: Deployment
metadata:
  name: basicdisplaydb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basicdisplaydb
  template:
    metadata:
      labels:
        app: basicdisplaydb
    spec:
      containers:
        - name: server
          image: postgres:14.1
          ports:
            - containerPort: 25432
              name: tcp-postgres
          envFrom:
            - configMapRef:
                name: basicdisplaydb
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: basicdisplaydb
      volumes:
      - name: basicdisplaydb
        persistentVolumeClaim:
          claimName: basicdisplaydb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: basicdisplaydb
  labels:
    app: postgres
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: changeme
  PGPORT: "25432"
---
apiVersion: v1
kind: Service
metadata:
  name: basicdisplaydb
spec:
  type: ClusterIP
  selector:
    app: basicdisplaydb
  ports:
    - name: tcp-postgres
      port: 25432
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: basicdisplaydb
spec:
  hosts:
    - basicdisplaydb
  http:
    - route:
        - destination:
            host: basicdisplaydb
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: basicdisplaydb
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: basicdisplaydb
  name: basicdisplaydb
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500M